name: ding_shi_ren_wu
on:
  schedule:
    # UTC时间，比中国时间慢8h, 昨天22:30 -> 今天6:30
    # 翻译：每周二、五、六的22:30触发，即中国时间，每周三、六、七的6:30触发，星期天为0
    #    - cron: '30 22 * * 2,4,5'
    #    - cron: '30 22 * * 4,5'
    #   每周一、五、六早上六点半触发，触发后预约明天的图书馆，即约周二、六、日的座位
#    - cron: '30 22 * * 1,5,6'
      - cron: '00 8 * * *'

jobs:
  build:
    runs-on: windows-latest
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install datetime
        pip install pathlib
        pip install urllib.parse
      

