name: ding_shi_ren_wu
on:
  schedule:
    #   每周一、五、六早上六点半触发，触发后预约明天的图书馆，即约周二、六、日的座位
    #    - cron: '30 22 * * 1,5,6'
    # 每天每小时，第0分钟开始，每五分钟运行一次
    - cron: '0/5 * * * *'


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install httpx
          pip install loguru
          pip install lxml

      - name: Run Reserve
        run: python reserve.py